name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: python-poetry/action@v3
      with:
        poetry-version: 1.8.1  # or the version you want to use
    - name: Install dependencies
      run: |
        poetry install
    - name: Reformat code with Black, Analyse the code with pytest and pylint
      run: |
        poetry run black $(git ls-files '*.py')
        poetry run pytest
        poetry run pylint $(git ls-files '*.py')